<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class TractorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tractors = [
            [
                'status' => 'Active',
                'tractor_id' => '001',
                'year' => '2021',
                'make' => 'Unknown',
                'model' => 'Tractor',
                'vin' => 'SCFAC23302B500083',
                'owned_by' => 'Unknown',
                'driver_1' => 'Unknown',
                'tag' => '1234567',
                'tag_expiration' => '2021-01-01',
                'tag_state' => 'NC',
                'last_inspection' => '2020-01-01',
                'comments' => 'This tractor was generated by the system.',
                'entered_by' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status' => 'Active',
                'tractor_id' => '002',
                'year' => '2022',
                'make' => 'Unknown',
                'model' => 'Tractor',
                'vin' => '1FABP21B4CK165368',
                'owned_by' => 'Unknown',
                'driver_1' => 'Unknown',
                'tag' => '1234567',
                'tag_expiration' => '2021-01-01',
                'tag_state' => 'NC',
                'last_inspection' => '2020-01-01',
                'comments' => 'This tractor was generated by the system.',
                'entered_by' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('tractors')->insert($tractors);
    }
}
