<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
use Str;

class TractorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
/**
 * Commented Out for Production
 *
        for ($i = 0; $i < 30000; $i++) {
            DB::table('tractors')->insert([
                'status' => 'Active',
                'tractor_id' => Str::random(10),
                'year' => '2021',
                'make' => 'Unknown',
                'model' => 'Tractor',
                'vin' => Str::random(9),
                'owned_by' => 'Unknown',
                'driver_1' => 'Unknown',
                'tag' => '1234567',
                'tag_expiration' => '2021-01-01',
                'tag_state' => 'NC',
                'last_inspection' => '2020-01-01',
                'comments' => 'This tractor was generated by the system.',
                'user_id' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
 */
    }
}
