<?php

namespace Database\Seeders;

use App\Models\Trailers;
use DB;
use Illuminate\Database\Seeder;
use Str;

class TrailerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            $trailers = [
                [
                    'status' => 'Active',
                    'trailer_id' => 'R001',
                    'year' => '2021',
                    'make' => 'Unknown',
                    'model' => 'Trailer',
                    'vin' => 'SCFAC23302B500083',
                    'equip_type_id' => 'RF',
                    'owned_by' => 'Unknown',
                    'tag' => '1234567',
                    'tag_expiration' => '2021-01-01',
                    'tag_state' => 'NC',
                    'last_inspection' => '2020-01-01',
                    'comments' => 'This tractor was generated by the system.',
                    'entered_by' => '4',
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            ];
                    DB::table('trailers')->insert($trailers);
    }
}
